services:
  - type: web
    name: CRUD-Evaluacion-Mensual
    runtime: dotnet
    repo: https://github.com/dcatalan03/CRUD_Evaluacion_Mensual_Abril
    branch: main
    buildCommand: dotnet build
    startCommand: dotnet run --urls=http://0.0.0.0:10000
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
    plan: free